[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["fetchcatalog"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "fetchcatalog"
  org = "wso2sa"
  version = "1.0.1"

